/**
 * Phase 8 Vision RAG — Modal worker (real, Sprint 8.9).
 *
 * Calls a Modal-hosted ColQwen2 endpoint over HTTPS. The endpoint is
 * expected to expose a single POST that takes a list of
 * { vision_page_id, image_url } and returns a list of
 * { vision_page_id, summary_vector[128], patch_vectors[64×128],
 *   model_used } per page.
 *
 * Configuration (env):
 *   VISION_GPU_HOST=modal             # routes via factory
 *   MODAL_API_KEY=<bearer token>      # sent as Authorization header
 *   MODAL_ENDPOINT_URL=<https://...>  # full POST URL
 *   MODAL_TIMEOUT_MS=120000           # optional, default 2 min
 *   MODAL_BATCH_SIZE=8                # optional, default 8 pages/call
 *
 * Failure modes:
 *   - Network error / timeout → all pages in the batch marked failed
 *     with the error message; the dispatcher records each per-page.
 *   - Per-page failures inside a successful HTTP response are honored
 *     (Modal returns success=false + error in the page object).
 *   - Dim mismatch / malformed shape → page marked failed; we never
 *     write a vector with wrong dim into vision_embeddings (the
 *     downstream guard would throw anyway, but we catch early for
 *     a cleaner per-page error message).
 *
 * The page-image bucket is private — pages are sent as signed URLs
 * (5-minute expiry) generated by getPageImageUrl. The Modal endpoint
 * fetches each URL once.
 */
import type { SupabaseClient } from '@supabase/supabase-js'
import type { GpuWorker, EmbedResult } from '../gpu-worker'
import type { VisionPage } from '../types'
import { getPageImageUrl } from '../storage'

export const MODAL_EMBEDDING_DIM = 128
export const MODAL_PATCH_COUNT_EXPECTED = 64
export const MODAL_DEFAULT_TIMEOUT_MS = 120_000
export const MODAL_DEFAULT_BATCH_SIZE = 8

interface ModalPageRequest {
  vision_page_id: string
  image_url: string
}

interface ModalPageResponse {
  vision_page_id: string
  summary_vector?: number[]
  patch_vectors?: number[][]
  model_used?: string
  success: boolean
  error?: string
}

interface ModalBatchResponse {
  results: ModalPageResponse[]
}

export interface ModalWorkerDeps {
  /** Supabase client used to mint signed URLs for the page images. */
  supabase: SupabaseClient
  /** Override env reads — for testability. */
  env?: {
    MODAL_API_KEY?: string
    MODAL_ENDPOINT_URL?: string
    MODAL_TIMEOUT_MS?: string
    MODAL_BATCH_SIZE?: string
  }
  /** Override fetch — for testability. */
  fetchFn?: typeof fetch
}

function readEnv(deps: ModalWorkerDeps, name: string): string | undefined {
  return deps.env?.[name as keyof NonNullable<ModalWorkerDeps['env']>] ??
    process.env[name]
}

function chunk<T>(arr: T[], size: number): T[][] {
  if (size <= 0) return [arr]
  const out: T[][] = []
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size))
  return out
}

function failResult(p: VisionPage, message: string): EmbedResult {
  return {
    vision_page_id: p.id,
    vision_index_id: '',
    embedding_dim: MODAL_EMBEDDING_DIM,
    model_used: 'colqwen2',
    success: false,
    error: message,
  }
}

function validateModalPage(
  resp: ModalPageResponse,
  p: VisionPage,
): EmbedResult {
  if (!resp.success) {
    return failResult(p, resp.error ?? 'modal reported failure without message')
  }
  if (!Array.isArray(resp.summary_vector) || resp.summary_vector.length !== MODAL_EMBEDDING_DIM) {
    return failResult(
      p,
      `bad summary_vector: expected length ${MODAL_EMBEDDING_DIM}, got ${resp.summary_vector?.length ?? 'undefined'}`,
    )
  }
  if (!Array.isArray(resp.patch_vectors) || resp.patch_vectors.length === 0) {
    return failResult(p, 'patch_vectors missing or empty')
  }
  // Each patch must match the embedding dim.
  for (let i = 0; i < resp.patch_vectors.length; i++) {
    const patch = resp.patch_vectors[i]
    if (!Array.isArray(patch) || patch.length !== MODAL_EMBEDDING_DIM) {
      return failResult(
        p,
        `patch ${i}: expected length ${MODAL_EMBEDDING_DIM}, got ${patch?.length ?? 'undefined'}`,
      )
    }
  }
  return {
    vision_page_id: p.id,
    vision_index_id: `modal_${p.id}`,
    embedding_dim: MODAL_EMBEDDING_DIM,
    model_used: resp.model_used ?? 'colqwen2',
    success: true,
    summary_vector: resp.summary_vector,
    patch_vectors: { patches: resp.patch_vectors },
  }
}

async function callModalBatch(
  endpointUrl: string,
  apiKey: string,
  pages: ModalPageRequest[],
  timeoutMs: number,
  fetchFn: typeof fetch,
): Promise<ModalBatchResponse> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const res = await fetchFn(endpointUrl, {
      method: 'POST',
      headers: {
        'authorization': `Bearer ${apiKey}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ pages }),
      signal: controller.signal,
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`modal endpoint ${res.status}: ${text.slice(0, 200)}`)
    }
    const json = (await res.json()) as ModalBatchResponse
    if (!json || !Array.isArray(json.results)) {
      throw new Error('modal endpoint returned malformed body (no results[])')
    }
    return json
  } finally {
    clearTimeout(timer)
  }
}

/**
 * Build the real Modal worker. The factory passes in the Supabase
 * client used to mint signed URLs.
 */
export function createModalWorker(deps: ModalWorkerDeps): GpuWorker {
  const fetchFn = deps.fetchFn ?? fetch

  return {
    id: 'modal',
    label: 'Modal (ColQwen2)',

    async embed(pages: VisionPage[]): Promise<EmbedResult[]> {
      const apiKey = readEnv(deps, 'MODAL_API_KEY')
      const endpointUrl = readEnv(deps, 'MODAL_ENDPOINT_URL')
      if (!apiKey || !endpointUrl) {
        // Hard-fail per page rather than silently fall back — the
        // factory only routes here when the keys ARE set, so missing
        // them at this layer is a programmer error worth surfacing.
        return pages.map((p) =>
          failResult(p, 'MODAL_API_KEY or MODAL_ENDPOINT_URL missing'),
        )
      }
      const timeoutMs = Number(readEnv(deps, 'MODAL_TIMEOUT_MS')) || MODAL_DEFAULT_TIMEOUT_MS
      const batchSize = Number(readEnv(deps, 'MODAL_BATCH_SIZE')) || MODAL_DEFAULT_BATCH_SIZE

      // Mint signed URLs for every page up-front. A failed signing
      // marks just that page failed — the rest of the batch proceeds.
      const urlMap = new Map<string, string>()
      const earlyFailures: EmbedResult[] = []
      for (const p of pages) {
        try {
          const url = await getPageImageUrl(deps.supabase, p.page_image_path, 300)
          if (!url) {
            earlyFailures.push(failResult(p, 'getPageImageUrl returned null'))
            continue
          }
          urlMap.set(p.id, url)
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err)
          earlyFailures.push(failResult(p, `signed url: ${message}`))
        }
      }

      const sendablePages = pages.filter((p) => urlMap.has(p.id))
      const results: EmbedResult[] = [...earlyFailures]
      const pageById = new Map(pages.map((p) => [p.id, p]))

      // Send in batches of MODAL_BATCH_SIZE so we don't blow up
      // serverless cold-start memory on a 100-page ingestion.
      for (const batch of chunk(sendablePages, batchSize)) {
        const requestPages: ModalPageRequest[] = batch.map((p) => ({
          vision_page_id: p.id,
          image_url: urlMap.get(p.id)!,
        }))
        try {
          const resp = await callModalBatch(endpointUrl, apiKey, requestPages, timeoutMs, fetchFn)
          // Map response back per page — a missing entry counts as failure.
          const respById = new Map(resp.results.map((r) => [r.vision_page_id, r]))
          for (const p of batch) {
            const r = respById.get(p.id)
            if (!r) {
              results.push(failResult(p, 'modal endpoint omitted page from response'))
              continue
            }
            results.push(validateModalPage(r, p))
          }
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err)
          // Whole-batch failure — flag every page in the batch.
          for (const p of batch) {
            results.push(failResult(p, `batch call failed: ${message}`))
          }
        }
      }

      // Restore input order — the dispatcher matches results by id
      // anyway, but ordered output makes test assertions trivial.
      const orderedResults: EmbedResult[] = []
      const resultsById = new Map(results.map((r) => [r.vision_page_id, r]))
      for (const p of pages) {
        const r = resultsById.get(p.id)
        if (r) orderedResults.push(r)
        else orderedResults.push(failResult(pageById.get(p.id)!, 'lost track of page'))
      }
      return orderedResults
    },
  }
}
