/**
 * POST /api/support/chat — AI-driven help chat from the unified launcher.
 *
 * Distinct from /api/support (which is the formal ticket-creation /
 * admin-inbox surface). This route is the conversational AI front-end:
 * a user types a question in the launcher, the support first-responder
 * agent answers, the Q + A get appended to a support_ticket row
 * (created on first turn) so the conversation is persistent + the admin
 * can audit it later.
 *
 * Body: { ticket_id?: string, message: string, persona?: string }
 * Response: { ticket_id, answer, confidence, cited_kb_ids, category,
 *             needs_human, follow_ups, agent_run_id }
 */
import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabase, createServiceSupabase } from '@/lib/supabase/server'
import { answerSupportQuestion } from '@/lib/agents/impl/support-first-responder'
import { triageTicket } from '@/lib/agents/impl/support-triage'

export const runtime = 'nodejs'
export const maxDuration = 60

export async function POST(req: NextRequest) {
  const supabase = createServerSupabase()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  let body: { ticket_id?: string; message?: string; persona?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }
  const question = (body.message ?? '').trim()
  if (!question || question.length > 4000) {
    return NextResponse.json({ error: 'message is required (max 4000 chars)' }, { status: 400 })
  }
  const persona = ((['owner', 'shop', 'mechanic', 'admin'].includes(body.persona ?? '')
    ? body.persona
    : 'owner') as 'owner' | 'shop' | 'mechanic' | 'admin')

  const service = createServiceSupabase()

  // Fetch or create the ticket. We use submitter_user_id (the existing
  // schema's column name) for ownership.
  let ticketId = body.ticket_id ?? null
  let priorMessages: Array<{ role: 'user' | 'assistant'; content: string; ts?: number }> = []

  if (ticketId) {
    const { data: existing } = await service
      .from('support_tickets')
      .select('id, messages, submitter_user_id')
      .eq('id', ticketId)
      .maybeSingle()
    if (!existing || existing.submitter_user_id !== user.id) {
      return NextResponse.json({ error: 'Ticket not found' }, { status: 404 })
    }
    priorMessages = (existing.messages as typeof priorMessages) ?? []
  } else {
    // Aligns with the canonical ticket taxonomy in lib/support/tickets.ts:
    // status ∈ { new | ai_triaging | awaiting_customer | awaiting_admin |
    //           resolved | closed }. We start at 'ai_triaging' because the
    // first-responder agent is about to run; we'll flip it to either
    // awaiting_customer (AI handled it) or awaiting_admin (needs_human=true)
    // immediately below.
    const subject = question.length > 80 ? question.slice(0, 77) + '…' : question
    // ticket_number is generated by the support_tickets_assign_number
    // trigger (migration 109) — we don't pass it. Source must be one of
    // the enum values {web_form, email, in_app, admin_created} —
    // launcher chat is in-app.
    const { data: created, error: insertErr } = await service
      .from('support_tickets')
      .insert({
        submitter_user_id: user.id,
        submitter_email: user.email ?? `${user.id}@unknown.local`,
        persona,
        status: 'ai_triaging',
        subject,
        body: question,
        source: 'in_app',
        messages: [],
        category: 'other',
        severity: 'P3',
      })
      .select('id')
      .single()
    if (insertErr || !created) {
      return NextResponse.json(
        { error: 'Could not create ticket', detail: insertErr?.message },
        { status: 500 },
      )
    }
    ticketId = (created as { id: string }).id
  }

  // Run the support first-responder agent
  const agentResult = await answerSupportQuestion({
    supabase: service,
    triggeredBy: user.id,
    ticketId: ticketId!,
    question,
    persona,
    priorTurns: priorMessages,
  })

  let answer = 'A human will follow up shortly.'
  let confidence: string = 'refused'
  let citedKbIds: string[] = []
  let category: string = 'other'
  let needsHuman = true
  let followUps: string[] = []

  if (agentResult.ok && agentResult.output) {
    const out = agentResult.output
    answer = out.answer
    confidence = out.confidence
    citedKbIds = out.cited_kb_ids
    category = out.category
    needsHuman = !!out.needs_human || out.confidence === 'refused' || out.confidence === 'low'
    followUps = out.follow_ups ?? []
  }

  // Map the agent's free-form category vocabulary onto the
  // support_ticket_category enum {billing, technical, feature_request,
  // bug, account, other}. The agent's vocab is broader (it includes
  // how-to, outage, security) — we collapse those onto the closest
  // enum value so the DB write doesn't fail.
  const dbCategory = (() => {
    switch (category) {
      case 'billing':
        return 'billing'
      case 'bug':
      case 'outage':
      case 'security':
        return 'bug'
      case 'feature-request':
        return 'feature_request'
      case 'how-to':
        return 'technical'
      default:
        return 'other'
    }
  })()

  // Chained: triage (category + severity). First turn only — repeated
  // triage on every reply would waste tokens. We await with a 2.5s race
  // budget so the response stays fast on the happy path but the agent's
  // audit row still completes (Vercel kills fire-and-forget promises
  // when the function returns, leaving rows stuck in 'running').
  if (priorMessages.length === 0) {
    const triagePromise = triageTicket({
      supabase: service,
      triggeredBy: user.id,
      ticketId: ticketId!,
      question,
      aiAnswer: answer,
    }).catch(() => undefined)
    await Promise.race([
      triagePromise,
      new Promise((resolve) => setTimeout(resolve, 2500)),
    ])
  }

  // Append both turns + update ticket
  const now = Date.now()
  const messages = [
    ...priorMessages,
    { role: 'user' as const, content: question, ts: now },
    { role: 'assistant' as const, content: answer, ts: Date.now() },
  ]
  // Map agent outcome onto the canonical TicketStatus union
  // (see lib/support/tickets.ts). needs_human → admin inbox queue;
  // otherwise the AI handled it and we wait on the customer.
  const nextStatus = needsHuman ? 'awaiting_admin' : 'awaiting_customer'
  await service
    .from('support_tickets')
    .update({
      messages,
      ai_confidence: confidence,
      category: dbCategory,
      cited_kb_ids: citedKbIds,
      status: nextStatus,
      ai_first_response_at:
        priorMessages.length === 0 ? new Date().toISOString() : undefined,
      updated_at: new Date().toISOString(),
    })
    .eq('id', ticketId!)

  return NextResponse.json({
    ticket_id: ticketId,
    answer,
    confidence,
    cited_kb_ids: citedKbIds,
    category,
    needs_human: needsHuman,
    follow_ups: followUps,
    agent_run_id: agentResult.runId,
  })
}
