// Auto-generated by: pnpm db:types
// Run: supabase gen types typescript --local > packages/database/types.ts
// This file is a placeholder — run the command above after setting up Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          plan: string
          plan_aircraft_limit: number
          plan_storage_gb: number
          plan_queries_monthly: number
          queries_used_this_month: number
          queries_reset_at: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['organizations']['Row']> & {
          name: string
          slug: string
        }
        Update: Partial<Database['public']['Tables']['organizations']['Row']>
      }
      // Add other tables as needed after running supabase gen types
    }
    Views: Record<string, never>
    Functions: {
      search_aircraft_documents: {
        Args: {
          p_organization_id: string
          p_aircraft_id: string | null
          p_query_embedding: number[]
          p_query_text: string
          p_doc_type_filter: string[] | null
          p_limit?: number
          p_vector_weight?: number
          p_keyword_weight?: number
        }
        Returns: Array<{
          chunk_id: string
          document_id: string
          document_title: string
          doc_type: string
          aircraft_id: string | null
          page_number: number
          section_title: string | null
          chunk_text: string
          metadata_json: Json
          vector_score: number
          keyword_score: number
          combined_score: number
        }>
      }
      get_my_org_ids: {
        Args: Record<string, never>
        Returns: string[]
      }
      has_org_role: {
        Args: { p_org_id: string; p_roles: string[] }
        Returns: boolean
      }
      increment_query_count: {
        Args: { p_org_id: string }
        Returns: void
      }
    }
    Enums: {
      doc_type: 'logbook' | 'poh' | 'afm' | 'afm_supplement' | 'maintenance_manual' | 'service_manual' | 'parts_catalog' | 'service_bulletin' | 'airworthiness_directive' | 'work_order' | 'inspection_report' | 'form_337' | 'form_8130' | 'lease_ownership' | 'insurance' | 'compliance' | 'miscellaneous'
      parsing_status: 'queued' | 'parsing' | 'chunking' | 'embedding' | 'completed' | 'failed' | 'needs_ocr' | 'ocr_processing'
      source_provider: 'direct_upload' | 'google_drive'
      query_confidence: 'high' | 'medium' | 'low' | 'insufficient_evidence'
    }
  }
}
