import type {
  DocumentMarketplaceType,
  MarketplacePartListing,
  PartLookupResult,
  SellerPlanDefinition,
} from '@/lib/marketplace/types'

export const MARKETPLACE_SELLER_PLANS: SellerPlanDefinition[] = [
  {
    id: 'starter',
    name: 'Starter',
    monthlyPrice: 25,
    listingLimit: 25,
    supportsVideo: false,
    supportsPriority: false,
    supportsAdvancedAnalytics: false,
    features: [
      'Up to 25 active parts listings',
      'AI-assisted listing creation',
      'Part number autofill',
      'Photo upload',
      'Direct buyer contact',
      'Mark sold / available / pending',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    monthlyPrice: 49.99,
    listingLimit: null,
    supportsVideo: true,
    supportsPriority: true,
    supportsAdvancedAnalytics: true,
    features: [
      'Unlimited active parts listings',
      'AI-assisted listing creation',
      'Part number autofill',
      'Photo + short video upload',
      'Direct buyer contact',
      'Priority ranking in search',
      'Advanced listing analytics',
    ],
  },
]

export const PART_MARKETPLACE_CATEGORIES = [
  'Engine & ignition',
  'Electrical & charging',
  'Avionics',
  'Landing gear & brakes',
  'Hydraulic & fuel',
  'Cabin & airframe',
  'Hardware & kits',
] as const

export const MANUAL_MARKETPLACE_TYPES: Array<{
  id: DocumentMarketplaceType
  label: string
}> = [
  { id: 'maintenance_manual', label: 'Maintenance Manual' },
  { id: 'service_manual', label: 'Service Manual' },
  { id: 'parts_catalog', label: 'Parts Catalog' },
  { id: 'ipc', label: 'IPC' },
  { id: 'wiring_manual', label: 'Wiring Manual' },
  { id: 'structural_repair_manual', label: 'Structural Repair Manual' },
  { id: 'overhaul_manual', label: 'Overhaul Manual' },
  { id: 'component_maintenance_manual', label: 'Component Maintenance Manual' },
  { id: 'document_other', label: 'Other Technical Document' },
]

export const MARKETPLACE_MANUFACTURERS = [
  'Cessna',
  'Piper',
  'Beechcraft',
  'Garmin',
  'Lycoming',
  'Continental',
  'Bendix',
  'Cleveland',
  'Tempest',
  'Hartzell',
]

export const PART_LOOKUP_SEEDS: PartLookupResult[] = [
  {
    normalizedPartNumber: '28V60A-ALT-C172',
    title: '28V 60A Alternator Assembly',
    manufacturer: 'Plane Power',
    category: 'Electrical & charging',
    alternatePartNumber: 'AL12-EI60/C',
    fitsApplicability: 'Cessna 172 / 182 (28V electrical systems)',
    description: 'Direct replacement alternator assembly with mounting hardware kit.',
    confidence: 'high',
  },
  {
    normalizedPartNumber: 'S4LN-21',
    title: 'Magneto S4LN-21',
    manufacturer: 'Bendix',
    category: 'Engine & ignition',
    alternatePartNumber: '10-382555-2',
    fitsApplicability: 'Lycoming four-cylinder ignition applications',
    description: 'Factory-overhauled magneto with data tag and bench test report.',
    confidence: 'high',
  },
  {
    normalizedPartNumber: '066-10500',
    title: 'GTX 335 ADS-B Out Transponder',
    manufacturer: 'Garmin',
    category: 'Avionics',
    alternatePartNumber: null,
    fitsApplicability: 'General aviation panel-mount transponder upgrades',
    description: 'Panel-mount transponder with ADS-B Out compliance support.',
    confidence: 'medium',
  },
  {
    normalizedPartNumber: 'SAF101',
    title: 'Spin-On Oil Filter',
    manufacturer: 'Tempest',
    category: 'Hardware & kits',
    alternatePartNumber: 'CH48110-1',
    fitsApplicability: 'Lycoming oil filter adapter installations',
    description: 'Standard spin-on oil filter with documented traceability.',
    confidence: 'high',
  },
]

export const SEEDED_PART_LISTINGS: MarketplacePartListing[] = [
  {
    id: 'demo-part-1',
    listingKind: 'part',
    title: '28V Alternator Assembly with Mount Kit',
    partNumber: '28V60A-ALT-C172',
    alternatePartNumber: 'AL12-EI60/C',
    manufacturer: 'Plane Power',
    category: 'Electrical & charging',
    subcategory: 'Alternators',
    condition: 'overhauled',
    priceCents: 185000,
    quantity: 1,
    location: 'Scottsdale, AZ',
    serialNumber: 'PP-44912',
    fitsApplicability: 'Cessna 172 / 182',
    description: 'Bench-tested alternator assembly with mounting bracket and install notes.',
    sellerNotes: 'Removed during avionics upgrade. Yellow-tagged and ready to ship.',
    traceDocsAvailable: true,
    tagAvailable: true,
    media: [],
    status: 'available',
    views: 132,
    contactMetrics: { call: 8, text: 5, email: 11, total: 24 },
    sellerId: 'demo-seller-1',
    sellerName: 'Blue Mesa Aero Supply',
    sellerPlan: 'pro',
    sellerPhone: '+14805550101',
    sellerTextNumber: '+14805550101',
    sellerEmail: 'sales@bluemesaaero.example',
    priorityRanked: true,
    createdAt: '2026-04-02T18:30:00.000Z',
    updatedAt: '2026-04-08T17:10:00.000Z',
  },
  {
    id: 'demo-part-2',
    listingKind: 'part',
    title: 'Overhauled Bendix Magneto S4LN-21',
    partNumber: 'S4LN-21',
    alternatePartNumber: '10-382555-2',
    manufacturer: 'Bendix',
    category: 'Engine & ignition',
    subcategory: 'Magnetos',
    condition: 'overhauled',
    priceCents: 124500,
    quantity: 2,
    location: 'Wichita, KS',
    serialNumber: null,
    fitsApplicability: 'Lycoming O-320 / O-360',
    description: 'Fresh overhaul with test bench sheet and documented trace.',
    sellerNotes: 'Sold individually or as a pair.',
    traceDocsAvailable: true,
    tagAvailable: true,
    media: [],
    status: 'available',
    views: 97,
    contactMetrics: { call: 2, text: 4, email: 6, total: 12 },
    sellerId: 'demo-seller-2',
    sellerName: 'Prairie Airframe & Powerplant',
    sellerPlan: 'starter',
    sellerPhone: '+13165550111',
    sellerTextNumber: '+13165550111',
    sellerEmail: 'parts@prairieaandp.example',
    priorityRanked: false,
    createdAt: '2026-04-01T14:05:00.000Z',
    updatedAt: '2026-04-07T10:25:00.000Z',
  },
  {
    id: 'demo-part-3',
    listingKind: 'part',
    title: 'GTX 335 ADS-B Out Transponder',
    partNumber: '066-10500',
    alternatePartNumber: null,
    manufacturer: 'Garmin',
    category: 'Avionics',
    subcategory: 'Transponders',
    condition: 'serviceable',
    priceCents: 219500,
    quantity: 1,
    location: 'San Antonio, TX',
    serialNumber: 'GTX335-11984',
    fitsApplicability: 'Panel-mount transponder upgrades',
    description: 'Removed from flying aircraft during glass panel upgrade. Includes tray and connector kit.',
    sellerNotes: 'Video walkaround available on Pro plan listing.',
    traceDocsAvailable: false,
    tagAvailable: false,
    media: [],
    status: 'available',
    views: 161,
    contactMetrics: { call: 5, text: 3, email: 9, total: 17 },
    sellerId: 'demo-seller-1',
    sellerName: 'Blue Mesa Aero Supply',
    sellerPlan: 'pro',
    sellerPhone: '+14805550101',
    sellerTextNumber: '+14805550101',
    sellerEmail: 'sales@bluemesaaero.example',
    priorityRanked: true,
    createdAt: '2026-04-05T09:20:00.000Z',
    updatedAt: '2026-04-09T21:40:00.000Z',
  },
  {
    id: 'demo-part-4',
    listingKind: 'part',
    title: 'Cleveland Wheel & Brake Assembly Kit',
    partNumber: '40-97A',
    alternatePartNumber: null,
    manufacturer: 'Cleveland',
    category: 'Landing gear & brakes',
    subcategory: 'Wheel assemblies',
    condition: 'serviceable',
    priceCents: 89500,
    quantity: 1,
    location: 'Lakeland, FL',
    serialNumber: null,
    fitsApplicability: 'Cessna / Piper light singles',
    description: 'Serviceable wheel and brake assembly with inspection tag.',
    sellerNotes: 'Ideal for owners keeping a spare shipset on the shelf.',
    traceDocsAvailable: true,
    tagAvailable: true,
    media: [],
    status: 'pending',
    views: 54,
    contactMetrics: { call: 1, text: 2, email: 2, total: 5 },
    sellerId: 'demo-seller-3',
    sellerName: 'Hangar 5 Components',
    sellerPlan: 'starter',
    sellerPhone: '+18635550141',
    sellerTextNumber: '+18635550141',
    sellerEmail: 'sales@hangar5components.example',
    priorityRanked: false,
    createdAt: '2026-03-29T11:15:00.000Z',
    updatedAt: '2026-04-06T13:00:00.000Z',
  },
  {
    id: 'demo-part-5',
    listingKind: 'part',
    title: 'Tempest Oil Filter Kit SAF101',
    partNumber: 'SAF101',
    alternatePartNumber: 'CH48110-1',
    manufacturer: 'Tempest',
    category: 'Hardware & kits',
    subcategory: 'Filters',
    condition: 'new_surplus',
    priceCents: 14500,
    quantity: 6,
    location: 'Tulsa, OK',
    serialNumber: null,
    fitsApplicability: 'Lycoming oil filter adapters',
    description: 'Factory-sealed filters from controlled shelf stock with trace paperwork.',
    sellerNotes: 'Sold as singles or case lot.',
    traceDocsAvailable: true,
    tagAvailable: false,
    media: [],
    status: 'available',
    views: 88,
    contactMetrics: { call: 0, text: 1, email: 4, total: 5 },
    sellerId: 'demo-seller-4',
    sellerName: 'Midwest Parts Vault',
    sellerPlan: 'starter',
    sellerPhone: '+19185550177',
    sellerTextNumber: '+19185550177',
    sellerEmail: 'inventory@midwestpartsvault.example',
    priorityRanked: false,
    createdAt: '2026-04-04T16:45:00.000Z',
    updatedAt: '2026-04-09T08:10:00.000Z',
  },
]
