import { requireAppServerSession } from '@/lib/auth/server-app'
import { Topbar } from '@/components/shared/topbar'
import { AIInbox } from '@/components/ai/ai-inbox'

export const metadata = { title: 'AI Inbox' }

/**
 * AI Inbox page (Spec 0.3) — stack of ActionCards generated by the
 * orchestrator. This is the home for the AI brain's output. Phase 5 will
 * replace the existing Dashboard with this component as the default
 * landing screen ("Smart Home Screen").
 */
export default async function InboxPage() {
  const { profile } = await requireAppServerSession()

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <Topbar profile={profile} breadcrumbs={[{ label: 'AI Inbox' }]} />
      <main className="flex-1 overflow-y-auto">
        <AIInbox />
      </main>
    </div>
  )
}
